[package]
name = "elevator_optimization"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
csv = "1.1"
