[package]
name = "elevator_optimization"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
egui = "0.16"
egui_glium = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
csv = "1.1"
